spring.application.name=backend-service

# Gemini AI
gemini.api.key=${GEMINI_API_KEY}

# HuggingFace
huggingface.api.key=${HUGGINGFACE_API_KEY}

# Database
spring.datasource.hikari.connection-timeout=30000

# Scraper
scraper.url=${SCRAPER_URL:http://localhost:8000}

# Endpoints de santé (pour Kubernetes)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true