spring.application.name=backend-service

# Gemini AI
gemini.api.key=${GEMINI_API_KEY}

# HuggingFace
huggingface.api.key=${HUGGINGFACE_API_KEY}

# Database
spring.datasource.hikari.connection-timeout=30000