kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: jobfit
nodes:
  - role: control-plane
    # Étiquette qui permettra d'installer l'Ingress sur ce nœud
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    # Relie les ports 80/443 de ton PC au cluster
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP